### ISSUE TITLE
LSCreditCardView

### ISSUE THREAD

**Issue by AbubakarGulzar** [Lopdo/LSCreditCardForm#1]
Hi
I trying to used LSCreditCardView showing added credit card list but i faced issue with layout, like in attached pic, when i adding lsview in my view hierarchy
![Simulator Screen Shot - iPhone 6s - 2019-04-21 at 01 10 34](https://user-images.githubusercontent.com/49821003/56461809-49908200-63d2-11e9-9937-d27ba5c5fdc4.png)
, card out my screen. Kindly guide me

**Comment by Lopdo** [comment]
Hello, could you please specify how are exactly are you adding views into the hierarchy? looks like it is too big, are constraints ok?

**Comment by AbubakarGulzar** [comment]
Yes constrains ok, I tried both way like from storyboard and code but same result, sample code screen shot attached, kindly guide what's wrong...
<img width="567" alt="Screen Shot 2019-04-21 at 9 05 21 AM" src="https://user-images.githubusercontent.com/49821003/56465323-a90f8180-6414-11e9-8b6d-53d89a996206.png">

**Comment by Lopdo** [comment]
You are not setting any constraints for the `LSCreditCardView` in your sample. 
try adding something like this after you add ls to vw as a subview:
```
vw.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "H:|[view]|", options: [], metrics: nil, views: ["view": ls]))
ls.topAnchor.constraint(equalTo: vw.topAnchor).isActive = true
vw.bottomAnchor.constraint(equalTo: ls.bottomAnchor).isActive = true
```

**Comment by AbubakarGulzar** [comment]
Thankx it's working
